name: montra_expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  flutter_svg: ^2.0.16
  dotted_border: ^2.1.0
  flutter_xlider: ^3.5.0

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  stacked_generator: ^1.6.1

# Material Design
flutter:
  uses-material-design: true
# Images
  assets:
    - assets/Icons/
    - assets/Icons/Arrows/
    - assets/Icons/Bank/
    - assets/Icons/Attachment/
    - assets/Icons/Finance/
    - assets/Icons/Profile/
    - assets/Icons/Edit/
    - assets/Images/User Image/
    - assets/Icons/Account View/
    - assets/Icons/Expanses Icons/
    - assets/Icons/Success/
    - assets/Icons/Errors/
    - assets/Icons/Delete/
# Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets\Fonts\Inter\Inter_28pt-Regular.ttf
        - asset: assets\Fonts\Inter\Inter_28pt-Black.ttf
          weight: 900
        - asset: assets\Fonts\Inter\Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets\Fonts\Inter\Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets\Fonts\Inter\Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets\Fonts\Inter\Inter_28pt-Medium.ttf
          weight: 500