name: montra_expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  flutter_svg: ^2.0.16
  dotted_border: ^2.1.0
  flutter_xlider: ^3.5.0
  fl_chart: ^0.69.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  flutter_spinkit: ^5.2.1
  google_sign_in: ^6.2.2
  fluttertoast: ^8.2.10
  shared_preferences: ^2.3.5

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  stacked_generator: ^1.6.1

# Material Design
flutter:
  uses-material-design: true
# Icons
  assets:
    - assets/Icons/Arrows/
    - assets/Icons/Attachment/
    - assets/Icons/Backgrounds/
    - assets/Icons/Bank/
    - assets/Icons/Bottom Navigation/
    - assets/Icons/Expanses/
    - assets/Icons/Finance/
    - assets/Icons/Graph/
    - assets/Icons/Graph/Line Chart/
    - assets/Icons/Graph/Pie Chart/
    - assets/Icons/Illustrations/
    - assets/Icons/Operations/
# Images
    - assets/Images/User Image/

# Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Fonts/Inter/Inter_28pt-Regular.ttf
        - asset: assets/Fonts/Inter/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/Fonts/Inter/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/Fonts/Inter/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Inter/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Inter/Inter_28pt-Medium.ttf
          weight: 500