name: montra_expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  flutter_svg: ^2.0.16

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  stacked_generator: ^1.6.1

# Material Design
flutter:
  uses-material-design: true
# Images
  assets:
    - assets/Icons/
    - assets/Icons/Arrows/
    - assets/Icons/Bank/
# Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets\Fonts\Inter\Inter_28pt-Regular.ttf
        - asset: assets\Fonts\Inter\Inter_28pt-Black.ttf
          weight: 900
        - asset: assets\Fonts\Inter\Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets\Fonts\Inter\Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Inter/Inter_28pt-SemiBold.ttf
          weight: 600