class IconsPath {
  static String backArrow = "assets/Icons/Arrows/back_arrow.svg";
  static String rightArrow = "assets/Icons/Arrows/right_arrow.svg";
  static String leftArrow = "assets/Icons/Arrows/left_arrow.svg";
  static String dropdownArrow = "assets/Icons/Arrows/down_arrow.svg";
  static String easypaisa = "assets/Icons/Bank/Easypaisa.svg";
  static String jazzcash = "assets/Icons/Bank/Jazz Cash.svg";
  static String ubl = "assets/Icons/Bank/UBL.svg";
  static String hbl = "assets/Icons/Bank/HBL.svg";
  static String sadapay = "assets/Icons/Bank/Sadapay.svg";
  static String attachment = "assets/Icons/Attachment/attachment.svg";
  static String transaction = "assets/Icons/Finance/transaction.svg";
  static String account = "assets/Icons/Profile/account.svg";
  static String settings = "assets/Icons/Profile/settings.svg";
  static String export = "assets/Icons/Profile/export.svg";
  static String logout = "assets/Icons/Profile/logout.svg";
  static String edit = "assets/Icons/Edit/edit.svg";
  static String accountBackground = "assets/Icons/Account View/background.svg";
  static String shopping = "assets/Icons/Expanses Icons/shopping.svg";
  static String food = "assets/Icons/Expanses Icons/food.svg";
  static String subscription = "assets/Icons/Expanses Icons/subscription.svg";
  static String transportation =
      "assets/Icons/Expanses Icons/transportation.svg";
  static String success = "assets/Icons/Success/success.svg";
  static String warning = "assets/Icons/Errors/warning.svg";
  static String delete = "assets/Icons/Delete/delete.svg";
  static String filter = "assets/Icons/Filter/filter.svg";
  static String salary = "assets/Icons/Finance/salary.svg";
  static String lineChart = "assets/Icons/Graph/Line Chart/line-chart.svg";
  static String pieChart = "assets/Icons/Graph/Pie Chart/pie-chart.svg";
  static String notification = "assets/Icons/Notification/notification.svg";
  static String income = "assets/Icons/Finance/income.svg";
  static String expense = "assets/Icons/Finance/expense.svg";
  static String close = "assets/Icons/Create/close.svg";
  static String home = "assets/Icons/Bottom Navigation/home.svg";
  static String userProfile = "assets/Icons/Bottom Navigation/user.svg";
  static String gainMoney = "assets/Icons/Illustrations/Gain Money.svg";
  static String trackMoney = "assets/Icons/Illustrations/Track Money.svg";
  static String plans = "assets/Icons/Illustrations/Plans.svg";
  static String show = "assets/Icons/Show/show.svg";
  static String google = "assets/Icons/Social/google.svg";
  static String deleteCharacter = "assets/Icons/Delete/delete character.svg";
  static String menuDots = "assets/Icons/Menu/menu dots.svg";
  static String camera = "assets/Icons/Attachment/camera.svg";
  static String gallery = "assets/Icons/Attachment/gallery.svg";
  static String document = "assets/Icons/Attachment/document.svg";
  static String currencyExchange =
      "assets/Icons/Bottom Navigation/currency-exchange.svg";
}
