class IconsPath {
  static String backArrow = "assets/Icons/Arrows/back_arrow.svg";
  static String rightArrow = "assets/Icons/Arrows/right_arrow.svg";
  static String leftArrow = "assets/Icons/Arrows/left_arrow.svg";
  static String dropdownArrow = "assets/Icons/Arrows/down_arrow.svg";
  static String easypaisa = "assets/Icons/Bank/Easypaisa.svg";
  static String jazzcash = "assets/Icons/Bank/Jazz Cash.svg";
  static String ubl = "assets/Icons/Bank/UBL.svg";
  static String hbl = "assets/Icons/Bank/HBL.svg";
  static String sadapay = "assets/Icons/Bank/Sadapay.svg";
  static String attachment = "assets/Icons/Attachment/attachment.svg";
  static String transaction = "assets/Icons/Finance/transaction.svg";
  static String account = "assets/Icons/Operations/account.svg";
  static String settings = "assets/Icons/Operations/settings.svg";
  static String export = "assets/Icons/Operations/export.svg";
  static String logout = "assets/Icons/Operations/logout.svg";
  static String edit = "assets/Icons/Operations/edit.svg";
  static String accountBackground = "assets/Icons/Backgrounds/background.svg";
  static String shopping = "assets/Icons/Expanses/shopping.svg";
  static String food = "assets/Icons/Expanses/food.svg";
  static String subscription = "assets/Icons/Expanses/subscription.svg";
  static String transportation = "assets/Icons/Expanses/transportation.svg";
  static String success = "assets/Icons/Operations/success.svg";
  static String warning = "assets/Icons/Operations/warning.svg";
  static String delete = "assets/Icons/Operations/delete.svg";
  static String filter = "assets/Icons/Operations/filter.svg";
  static String salary = "assets/Icons/Finance/salary.svg";
  static String lineChart = "assets/Icons/Graph/Line Chart/line-chart.svg";
  static String pieChart = "assets/Icons/Graph/Pie Chart/pie-chart.svg";
  static String notification = "assets/Icons/Operations/notification.svg";
  static String income = "assets/Icons/Finance/income.svg";
  static String expense = "assets/Icons/Finance/expense.svg";
  static String close = "assets/Icons/Operations/close.svg";
  static String home = "assets/Icons/Bottom Navigation/home.svg";
  static String userProfile = "assets/Icons/Bottom Navigation/user.svg";
  static String gainMoney = "assets/Icons/Illustrations/Gain Money.svg";
  static String trackMoney = "assets/Icons/Illustrations/Track Money.svg";
  static String plans = "assets/Icons/Illustrations/Plans.svg";
  static String show = "assets/Icons/Operations/show.svg";
  static String google = "assets/Icons/Operations/google.svg";
  static String deleteCharacter =
      "assets/Icons/Operations/delete character.svg";
  static String menuDots = "assets/Icons/Operations/menu dots.svg";
  static String camera = "assets/Icons/Attachment/camera.svg";
  static String gallery = "assets/Icons/Attachment/gallery.svg";
  static String document = "assets/Icons/Attachment/document.svg";
  static String currencyExchange =
      "assets/Icons/Bottom Navigation/currency-exchange.svg";
}
